name: deep_learning
channels:
  - conda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - keras-tuner
  - pip:
      - pyhere
